//! `ax init`: writes a starter `axonal.toml` describing the discovered workspace.

use std::path::Path;

use crate::{
    config, git,
    graph::{self, Workspace},
};

pub fn write(root: &Path, force: bool) -> anyhow::Result<()> {
    let path = root.join(config::FILE);
    anyhow::ensure!(
        force || !path.exists(),
        "{} already exists (pass --force to overwrite)",
        path.display()
    );
    let ws = Workspace::discover(root)?;
    let branch = git::default_branch(root).unwrap_or_else(|| "main".into());
    std::fs::write(&path, render(&ws, &branch))?;
    println!("wrote {} ({} projects)", path.display(), ws.projects.len());
    Ok(())
}

pub fn render(ws: &Workspace, branch: &str) -> String {
    let projects: String = ws
        .projects
        .values()
        .map(|p| {
            let kinds = p
                .kinds
                .iter()
                .map(|k| k.as_str())
                .collect::<Vec<_>>()
                .join("+");
            format!(
                "#   {} ({}, {kinds})\n",
                p.name,
                graph::display_root(&p.root)
            )
        })
        .collect();
    format!(
        "# Generated by `ax init`. Discovered {} projects:\n{projects}\n\
         [workspace]\ndefault_branch = {branch:?}\n\n\
         [targets.build]\ndepends_on = [\"^build\"]\n\n\
         [targets.test]\ndepends_on = [\"^build\"]\n",
        ws.projects.len()
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::graph::testing::{project, workspace};

    #[test]
    fn render_lists_projects_and_starter_targets() {
        let mut web = project("@acme/web", &[], &[]);
        web.root = "apps/web".into();
        web.kinds = [crate::graph::Kind::Js].into();
        let text = render(&workspace(vec![web]), "trunk");
        assert!(text.contains("#   @acme/web (apps/web, js)\n"), "{text}");
        assert!(text.contains("default_branch = \"trunk\""), "{text}");
        crate::config::Config::parse(&text, Path::new("axonal.toml")).unwrap();
    }
}
